name: PlayerMessage
version: '${project.version}'
main: playermessage.playermessage.PlayerMessage
api-version: 1.18
authors: [ tw_abc ]
softdepend: [ PlaceholderAPI ]
commands:
  playermessage:
  m:
  msg:
  tell:
