name: PlayerJoinLeave
version: '${project.version}'
main: playerjoinleave.playerjoinleave.PlayerJoinLeave
api-version: 1.18
authors: [ tw_abc ]
softdepend: [ PlaceholderAPI ]
commands:
  joinleave:
  m:
  msg:
  tell:
